// <auto-generated />
using CadastroProduto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadastroProduto.Migrations
{
    [DbContext(typeof(ContextoDb))]
    partial class ContextoDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("CadastroProduto.Model.Produto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricao");

                    b.Property<double>("Estoque")
                        .HasColumnType("double")
                        .HasColumnName("estoque");

                    b.Property<double>("Preco")
                        .HasColumnType("double")
                        .HasColumnName("preco");

                    b.HasKey("Codigo");

                    b.ToTable("produto");

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Descricao = "Caneta azul",
                            Estoque = 7.0,
                            Preco = 1.7
                        },
                        new
                        {
                            Codigo = 2,
                            Descricao = "Lápis",
                            Estoque = 16.0,
                            Preco = 0.59999999999999998
                        },
                        new
                        {
                            Codigo = 3,
                            Descricao = "Régua 20cm",
                            Estoque = 9.0,
                            Preco = 3.8999999999999999
                        },
                        new
                        {
                            Codigo = 4,
                            Descricao = "Pct sulfite A4 c/ 100",
                            Estoque = 23.0,
                            Preco = 9.8000000000000007
                        },
                        new
                        {
                            Codigo = 5,
                            Descricao = "Caneta marca texto amarela",
                            Estoque = 4.0,
                            Preco = 5.2999999999999998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
